### PR TITLE
fix types

### PR DESCRIPTION
**Pull request by KollerZx**
Correction in module types file

### CODE REVIEW

**Comment by s1gtrap** [comment]
I was about to submit this myself as `index.d.ts` is quite.. broken. 

You'd get something like
```
error TS2306: File '/home/s1g/example/node_modules/utm-latlng/index.d.ts' is not a module.
```
when trying to import the latest release.

**Comment by mheusch-trimble** [comment]
@shahid28 why not merge this?

**Comment by sirimykland** [comment]
it would be great to have this included in a new release @shahid28 🙌

**Comment by shahid28** [comment]
Fixed in new commit

**Pull request closed without merging**
